fix(ScalaLangDoc): ScDocTag.getAllText() -> getText()
incompatible with IntelliJ IDEA Ultimate IU-232.10300.40 due to the following problem
Method not found (1 problem)
Invocation of unresolved method ScDocTag.getAllText() (1 problem)
Method ScalaLangDoc.appendTag(...) contains an invokeinterface instruction referencing an unresolved method ScDocTag.getAllText(). This can lead to NoSuchMethodError exception at runtime.